### ISSUE TITLE
运行之后直接报错，找不到文件啊。是不是我太菜了。

### ISSUE THREAD

**Issue by zzz1233** [Ed1s0nZ/cool#1]
![image](https://user-images.githubusercontent.com/48712075/142189617-ae87da3c-1b1e-4c4c-9d9d-7d49b866be34.png)

**Comment by evi1hack** [comment]
![image](https://user-images.githubusercontent.com/16398717/142196015-f7c990a0-26ac-424a-8784-d6a0dc1cbae1.png)

按照这个操作。。。
