### ISSUE TITLE
为什么生成后自动下载都是0kb

### ISSUE THREAD

**Issue by sDreamForZzQ** [Ed1s0nZ/cool#2]
为什么生成后自动下载都是0kb

**Comment by wpsec** [comment]
+1

**Comment by Ed1s0nZ** [comment]
我下载测试没问题欸。。。

**Comment by Ed1s0nZ** [comment]
感觉可能是环境问题，执行一下这个 go env -w GO111MODULE=on

**Comment by sDreamForZzQ** [comment]
有执行过

**Comment by Ed1s0nZ** [comment]
是win10，还是win7，还是？

**Comment by sDreamForZzQ** [comment]
w7

**Comment by sDreamForZzQ** [comment]
![image](https://user-images.githubusercontent.com/49384664/142831524-c4da2d35-7110-42f6-abb5-959027917d35.png)

**Comment by Ed1s0nZ** [comment]
应该是混淆的问题，不支持win7，用win10试一下？或者本机装一下

**Comment by sDreamForZzQ** [comment]
哦哦，拿w10试试

**Comment by wpsec** [comment]
> 应该是重装的问题，不支持win7，用win10试一下？

我是win10环境，也不行，报 The system cannot find the file specified 错误

**Comment by wpsec** [comment]
![image](https://user-images.githubusercontent.com/57949806/142832006-2d884baa-84b8-4cc6-9d1e-d7fd5c5d2aad.png)

**Comment by sDreamForZzQ** [comment]
![image](https://user-images.githubusercontent.com/49384664/142832188-24ebbe4c-03c8-4aa2-b286-8902984d0aec.png)

**Comment by sDreamForZzQ** [comment]
一样的报错

**Comment by Ed1s0nZ** [comment]
我知道了，我马上更新！

**Comment by Ed1s0nZ** [comment]
我的问题，抱歉

**Comment by Ed1s0nZ** [comment]
先用第一个Releases吧，那里免杀的可以用；第二个的捆绑好像也能用，你们先结合的用一下，我排一下错就更新

**Comment by Ed1s0nZ** [comment]
你俩谁方便加我一下，

**Comment by Ed1s0nZ** [comment]
已更新，再尝试用一下

**Comment by sDreamForZzQ** [comment]
我用w7试着还是生成0kb

**Comment by Ed1s0nZ** [comment]
win10 试试吧

**Comment by Ed1s0nZ** [comment]
或者搭建在真机，我找人测试说成功了，你再试试吧

**Comment by sDreamForZzQ** [comment]
win10确实好使了

**Comment by Ed1s0nZ** [comment]
那我关闭了啊
