### ISSUE TITLE
生成的exe无法在目标机器上运行

### ISSUE THREAD

**Issue by qwgrsftewg** [Ed1s0nZ/cool#5]
![image](https://user-images.githubusercontent.com/64349502/143413190-0f856a21-3d6f-4b0f-89dd-1ffab7eb34f6.png)

**Comment by qwgrsftewg** [comment]
你这个选项后面标注了一个.zip是什么意思，意思是要把下载下来的txt改为zip后缀吗？我改了，但是解压软件无法打开
另外，与此同时，控制台输出报错：
![image](https://user-images.githubusercontent.com/64349502/143414300-ff3b8517-c99e-4685-ba35-c6d5b6426b10.png)
显示说找不到 D:/cool/2mrBU.zip文件，这个文件确实不存在但是存在同名的exe文件，我放到目标机器上直接就报毒了：
![image](https://user-images.githubusercontent.com/64349502/143414476-f8edf39e-2d04-4beb-8b18-f7ba19f95535.png)
杀软是windows 10 defender

**Comment by qwgrsftewg** [comment]
我都试了一遍，全都被defender识别为病毒了

**Comment by Ed1s0nZ** [comment]
bypass好像已经不行了，至于生成0kb，参考一下以下：
![图片](https://user-images.githubusercontent.com/83812544/143421184-c798720d-afc7-4898-a7ac-1ed5f04281af.png)

bypass不能了的话等更新吧，最近有点忙

**Comment by qwgrsftewg** [comment]
好的，谢谢回复
