### ISSUE TITLE
只有C盘用不了呀

### ISSUE THREAD

**Issue by NyDubh3** [Ed1s0nZ/cool#6]
能不能加个参数让我们可以自定义盘符

**Comment by Ed1s0nZ** [comment]
能是能，有点麻烦，😅

**Comment by NyDubh3** [comment]
大佬大佬

**Comment by y1s3m0** [comment]
subst.exe [Driver1: [Driver2:] Path]

**Comment by ghost** [comment]
虚拟机不能运行
结果都是0字节的 跟不是D盘有关系吗？

**Comment by SnowMeteors** [comment]
> 虚拟机不能运行 结果都是0字节的 跟不是D盘有关系吗？

只能放在d盘，其他盘都无法正常运行

**Comment by yundiao** [comment]
> > 虚拟机不能运行 结果都是0字节的 跟不是D盘有关系吗？
> 
> 只能放在d盘，其他盘都无法正常运行

虚拟机新建了D盘并置于D盘后，生成免杀一直报错，生成文件0字节；报错如下：
出错了：open D:/cool/xxxxx.exe：The system cannot find the file specified.

**Comment by Ed1s0nZ** [comment]
用win10，win7不太行。
换win10如果还不行的话，看看readme，是不是自己漏掉啥了。。。
