### ISSUE TITLE
报错以及产生的txt文件是0kb

### ISSUE THREAD

**Issue by XKaguya** [Ed1s0nZ/cool#9]
如题
![RO924IU8$B$_1C2}(K)YV{7](https://user-images.githubusercontent.com/96401952/146706522-c178426c-2887-4c4e-b45e-0f25359b6f4b.png)
该怎么解决

**Comment by Ed1s0nZ** [comment]
装git

**Comment by XKaguya** [comment]
![1639975076(1)](https://user-images.githubusercontent.com/96401952/146712604-b81e8bb0-c491-448d-ae78-97d4c9601f3c.jpg)
现在这样了 挂了梯子

**Comment by XKaguya** [comment]
啊这 梯子换了个节点好像没事了
